vcenter_server = "vcenter.balmerfamilyfarm.com"
vcenter_cluster = "operations"
vcenter_datacenter = "farm"
vcenter_datastore = "vsanDatastore"
vcenter_folder = "Templates"
vm_network = "vlan21-endpoints"